{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/leozinx244/Leonardo-Muniz/blob/main/Conhe%C3%A7a_o_Colab.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Wf5KrEb6vrkR"
      },
      "source": [
        "# Conheça o Colab"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import csv\n",
        "\n",
        "dados = [\n",
        "    ['Nome', 'Idade'],\n",
        "    ['Ana', 19  ],\n",
        "    ['Leo', 20],\n",
        "    ['Lucas', 13  ],\n",
        "    ['Elza', 58  ],\n",
        "    ['Iza', 56  ],\n",
        "    ['Ana Paula', 23  ],\n",
        "    ['Gustavo', 22  ],\n",
        "    ['Edmar', 42  ],\n",
        "    ['Patricia', 42  ],\n",
        "    ['Jeissy', 26  ],\n",
        "    ['Iago', 25  ],\n",
        "    ['Sofia', 17  ]\n",
        "]\n",
        "\n",
        "with open('dados.csv', mode='w', newline='', encoding='utf-8') as arquivo:\n",
        "    escritor = csv.writer(arquivo)\n",
        "    escritor.writerows(dados)"
      ],
      "metadata": {
        "id": "8vhCawC6MQUi"
      },
      "execution_count": 124,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "\n",
        "caminho_arquivo = 'dados.csv'\n",
        "\n",
        "df = pd.read_csv(\n",
        "    caminho_arquivo,\n",
        "    sep=',',\n",
        "    engine='python',\n",
        "    encoding='utf-8'\n",
        ")\n",
        "\n",
        "print(df.head())\n",
        "\n",
        "df.to_csv(\n",
        "    caminho_arquivo,\n",
        "    sep=';',\n",
        "    index=False,\n",
        "    encoding='utf-8'\n",
        ")\n",
        "\n",
        "print(\"Dados atualizados e salvos com sucesso.\")\n",
        "\n",
        "df_subconjunto = df[['Nome', 'Idade']]\n",
        "\n",
        "print(df_subconjunto.head())\n",
        "print(f\"Colunas selecionadas: {df_subconjunto.columns.tolist()}\")\n",
        "\n",
        "df_subconjunto.to_csv(\n",
        "    'subconjunto_dados.csv',\n",
        "    sep=';',\n",
        "    index=False,\n",
        "    encoding='utf-8'\n",
        ")\n",
        "\n",
        "print(\"Arquivo salvo com sucesso.\")\n",
        "\n",
        "pd.set_option('display.max_rows', 9999)\n",
        "\n",
        "df.to_csv(\n",
        "    'seu_arquivo.csv',\n",
        "    sep=';',\n",
        "    index=False,\n",
        "    encoding='utf-8'\n",
        ")\n",
        "\n",
        "print(df.to_string())\n",
        "\n",
        "print(df.head(10))\n",
        "\n",
        "print(df.tail(10))\n",
        "\n",
        "df.info()\n",
        "\n",
        "total_linhas = df.shape[0]\n",
        "\n",
        "total_colunas = df.shape[1]\n",
        "\n",
        "dados_nulos = df.isnull().sum()\n",
        "total_nulos_geral = dados_nulos.sum()\n",
        "\n",
        "tipos_dados = df.dtypes\n",
        "\n",
        "memoria_utilizada = df.memory_usage(deep=True).sum()\n",
        "\n",
        "print(f\"\\n--- Resumo Extraído ---\")\n",
        "print(f\"Total de linhas: {total_linhas}\")\n",
        "print(f\"Total de colunas: {total_colunas}\")\n",
        "print(f\"Total de dados nulos no conjunto: {total_nulos_geral}\")\n",
        "print(f\"\\nDetalhe de nulos por coluna:\\n{dados_nulos}\")\n",
        "print(f\"\\nTipos de dados por coluna:\\n{tipos_dados}\")\n",
        "print(f\"\\nMemória utilizada: {memoria_utilizada} bytes ({memoria_utilizada / 1024:.2f} KB)\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "rPivL3dJMkMw",
        "outputId": "a63c6be7-cb7d-4e23-d77d-c57d8e0fb378"
      },
      "execution_count": 125,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "    Nome  Idade\n",
            "0    Ana     19\n",
            "1    Leo     20\n",
            "2  Lucas     13\n",
            "3   Elza     58\n",
            "4    Iza     56\n",
            "Dados atualizados e salvos com sucesso.\n",
            "    Nome  Idade\n",
            "0    Ana     19\n",
            "1    Leo     20\n",
            "2  Lucas     13\n",
            "3   Elza     58\n",
            "4    Iza     56\n",
            "Colunas selecionadas: ['Nome', 'Idade']\n",
            "Arquivo salvo com sucesso.\n",
            "         Nome  Idade\n",
            "0         Ana     19\n",
            "1         Leo     20\n",
            "2       Lucas     13\n",
            "3        Elza     58\n",
            "4         Iza     56\n",
            "5   Ana Paula     23\n",
            "6     Gustavo     22\n",
            "7       Edmar     42\n",
            "8    Patricia     42\n",
            "9      Jeissy     26\n",
            "10       Iago     25\n",
            "11      Sofia     17\n",
            "        Nome  Idade\n",
            "0        Ana     19\n",
            "1        Leo     20\n",
            "2      Lucas     13\n",
            "3       Elza     58\n",
            "4        Iza     56\n",
            "5  Ana Paula     23\n",
            "6    Gustavo     22\n",
            "7      Edmar     42\n",
            "8   Patricia     42\n",
            "9     Jeissy     26\n",
            "         Nome  Idade\n",
            "2       Lucas     13\n",
            "3        Elza     58\n",
            "4         Iza     56\n",
            "5   Ana Paula     23\n",
            "6     Gustavo     22\n",
            "7       Edmar     42\n",
            "8    Patricia     42\n",
            "9      Jeissy     26\n",
            "10       Iago     25\n",
            "11      Sofia     17\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 12 entries, 0 to 11\n",
            "Data columns (total 2 columns):\n",
            " #   Column  Non-Null Count  Dtype \n",
            "---  ------  --------------  ----- \n",
            " 0   Nome    12 non-null     object\n",
            " 1   Idade   12 non-null     int64 \n",
            "dtypes: int64(1), object(1)\n",
            "memory usage: 324.0+ bytes\n",
            "\n",
            "--- Resumo Extraído ---\n",
            "Total de linhas: 12\n",
            "Total de colunas: 2\n",
            "Total de dados nulos no conjunto: 0\n",
            "\n",
            "Detalhe de nulos por coluna:\n",
            "Nome     0\n",
            "Idade    0\n",
            "dtype: int64\n",
            "\n",
            "Tipos de dados por coluna:\n",
            "Nome     object\n",
            "Idade     int64\n",
            "dtype: object\n",
            "\n",
            "Memória utilizada: 878 bytes (0.86 KB)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "1IpDV_wvO_pS"
      },
      "execution_count": 125,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "name": "Conheça o Colab",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
